const stringsVietnam = {
    "noti": "Thông báo",
    "noti_logout": "Bạn có muốn đăng xuất không ?",
    "option_yes" : "Đồng ý",
    "option-no": "Không",
    "category": "Danh mục",
    "author": "Tác giả",
    "price": "Giá",
    "updatedAt": "Ngày đăng",
    "rating": "Đánh giá",
    "totalHours": "Thời lượng",
    "noData": "Không có dữ liệu",
    "noCourse": "Không có khoá học nào",
    "hour": "giờ",
    "recommendCourses": "Gợi ý cho bạn",
    "topNew": "Mới nhất",
    "topSell": "Bán nhiều nhất",
    "topRate": "Đánh giá cao nhất",
    "processCourses": "Khoá học đang học",
    "favoriteCourses": "Khoá học yêu thích",
    "point": "Điểm",
    "type": "Loại người dùng",
    "changePass": "Thay đổi mật khẩu",
    "changeAvt": "Thay đổi ảnh đại diện",
    "changeTheme": "Thay đổi theme",
    "changeLan": "Thay đổi ngôn ngữ",
    "phone": "Điện thoại",
    "password": "Mật khẩu",
    "name": "Họ tên",
    "update": "Cập nhật",
    "updateYes": "Cập nhật thành công",
    "updateYes2": "Cập nhật thành công. Vui lòng đăng nhập lại tài khoản",
    "updateNo": "Cập nhật thất bại",
    "english": "Tiếng Anh",
    "vietnam": "Tiếng Việt",
    "light": "Tươi sáng",
    "dark": "Bóng tối",
    "instructor": "Giảng viên",
    "placeholderSearch": "Nhập ở đây...",
    "viewAll": "Xem tất cả",
    "viewMore": "Xem thêm",
    "downloadCourse": "Khoá học đã tải",
    "browse": "Khám phá",
    "setting": "Cài đặt",
    "search": "Tìm kiếm",
    "updateAcc": "Cập nhật thông tin",
    "viewAcc":"Xem tài khoản",
    "currentPass": "Mật khẩu hiện tại",
    "newPass": "Nhập mật khẩu mới",
    "confirmPass": "Xác nhận mật khẩu mới",
    "banned": "Bạn không được thay đổi dữ liệu của trường này",
    "language": "Ngôn ngữ",
    "shareApp": "Chia sẻ ứng dụng",
    "shareCourse": "Chia sẻ khoá học",
    "showExercises": "Bài tập",
    "pay": "Mua khoá học",
    "about": "Về chúng tôi",
    "version": "Phiên bản",
    "logout": "Đăng xuất",
    "aboutContent": "Phát triển bởi Lê Huỳnh Phúc. Ứng dụng dùng để tham gia các khoá học trực tuyến về lĩnh vực IT. bạn sẽ nhận được các khoá học xu hướng với đội ngũ giảng viên chuyển sâu",
    "noHistory": "Không có lịch sử tìm kiếm",
    "noContent": "Rất nhiều khoá học đang chờ bạn tìm kiếm và khám phá",
    "noBT":"Không có bài tập nào",
    "History": "Lịch sử tìm kiếm",
    "All": "Tất cả",
    "Author": "Tác giả",
    "Course": "Khoá học",
    "noEmpty":"Chưa nhập từ khoá tìm kiếm",
    "resultSearch": "kết quả",
    "resultSearch2": "Kết quả tìm kiếm",
    "home":"Trang chủ",
    "download": "Tải xuống",
    "login": "Đăng nhập",
    "register": "Đăng ký",
    "forgetPass": "Quên mật khẩu",
    "emailForgetPass": "Nhập Email để xác nhận",
    "verify":"Xác nhận",
    "detailCourse": "Chi tiết khoá học",
    "relatedCourse": "Các khoá học liên quan",
    "study": "Bắt đầu học",
    "typingRating": "Nhập đánh giá của bạn",
    "send": "Gửi",
    "deleteHistory": "Bạn có muốn xoá từ này không?",
    "totalHours": "Tổng số giờ: ",
    "totalVideo": "Tổng số bài học: ",
    "sold": "Số lượng đã bán",
    "status": "Tình trạng",
    "addRating": "Thêm đánh giá",
    "lastedUpdate": "Cập nhật lần cuối",
    "Like":"Thích",
    "Unlike": "Bỏ thích",
    "note-forget": "Hệ thống đã gửi link reset mật khẩu trong email của bạn. Vui lòng kiểm tra và đổi mật khẩu mới",
    "confirmPassword": "Xác nhận mật khẩu",
    "note-send": "Bạn có muốn gửi không?",
    "payment": "Bạn chưa đăng ký/mua khoá học này nên không thể truy cập",
    "payment2": "Bạn chưa đăng ký/mua khoá học này nên không thể truy cập. Banh muốn đăng ký miễn phí không?",

}

const stringsEnglish = {
    "payment": "You cannot access video because you haven't register",
    "payment2": "You cannot access video because you haven't register. Do you want register?",
    "note-send": "Do you want to send?",
    "confirmPassword": "Confirm Password",
    "note-forget": "System sent code in your email. Please access email and change new password",
    "Like":"Add to favorite courses",
    "Unlike": "Remove from favorite courses",
    "shareCourse": "Share course",
    "showExercises": "Exercises",
    "noBT":"No Exercise",
    "pay": "Buy this course",
    "noti": "Notification",
    "noti_logout": "Do you want to exit app?",
    "option_yes" : "Yes",
    "option-no": "No",
    "category": "Category",
    "author": "Author",
    "price": "Price",
    "updatedAt": "Updated At",
    "rating": "Rating",
    "totalHours": "Total Hours",
    "noData": "No data display",
    "noCourse": "No course display",
    "hour": "hour",
    "recommendCourses": "Recommend for you",
    "topNew": "Top New",
    "topSell": "Top Selling",
    "topRate": "Top Rating",
    "processCourses": "My Process Courses",
    "favoriteCourses": "My Favorite Courses",

    "point": "Point",
    "type": "Type",
    "changePass": "Change Password",
    "changeAvt": "Change Avatar",
    "phone": "Phone",
    "password": "Password",
    "name": "Full Name",
    "update": "Update",
    "updateYes": "Update Successfully",
    "updateYes2": "Update Successfully. Please login again",
    "updateNo": "Update Fail",
    "english": "English",
    "vietnam": "Vietnamese",
    "light": "Light",
    "dark": "Dark",
    "instructor": "Instructors",
    "placeholderSearch": "Type something...",
    "viewAll": "See all",
    "viewMore": "See more",
    "download": "Download",
    "downloadCourse": "Downloaded Courses",
    "browse": "Browser",
    "setting": "Setting",
    "search": "Search",
    "changeTheme": "Change Theme",
    "changeLan": "Change Language",
    "updateAcc": "Update Profile",
    "viewAcc":"View Account",
    "currentPass": "Current Password",
    "newPass": "New Password",
    "confirmPass": "Confirm New Password",
    "banned": "You must not change data in this field",
    "language": "Language",
    "shareApp": "Share app",
    "about": "About us",
    "version": "Version",
    "logout": "Logout",
    "aboutContent": "Developed by Le Huynh Phuc. This app allows user to participate in many different courses about IT. You will receive a lot of trending coures which are taught by famous and experienced instructors",
    "noHistory": "No history search",
    "noContent": "Search & explore many courses",
    "History": "Search History",
    "All": "All",
    "Author": "Author",
    "Course": "Course",
    "noEmpty":"You haven't typed keyword",
    "resultSearch": "results",
    "resultSearch2": "Result Search",
    "home":"Home",
    "login": "Login",
    "register": "Register",
    "forgetPass": "Forget Password",
    "emailForgetPass": "Enter email to verify...",
    "verify":"Verify",
    "detailCourse": "Detail Course",
    "relatedCourse": "Related Courses",
    "study": "Start studying",
    "typingRating": "Leave a comment",
    "send": "Send",
    "deleteHistory": "Do you want to delete this word?",
    "totalHours": "Total Hours ",
    "totalVideo": "Total Number of Videos: ",
    "sold": "Number of sold:",
    "status": "Status: ",
    "addRating": "Add your rating:",
    "lastedUpdate": "Lasted Update:",

}

const vietnam = JSON.stringify(stringsVietnam);
const english = JSON.stringify(stringsEnglish);

export { vietnam, english};