const stringsVietnam = {
    "noti": "Thông báo",
    "noti_logout": "Bạn có muốn đăng xuất không ?",
    "option_yes" : "Đồng ý",
    "option-no": "Không",
    "category": "Danh mục",
    "author": "Tác giả",
    "price": "Giá",
    "updatedAt": "Ngày đăng",
    "rating": "Đánh giá",
    "totalHours": "Thời lượng",
    "noData": "Không có dữ liệu",
    "noCourse": "Không có khoá học nào",
    "hour": "giờ",
    "recommendCourses": "Gợi ý cho bạn",
    "topNew": "Mới nhất",
    "topSell": "Bán nhiều nhất",
    "topRate": "Đánh giá cao nhất",
    "processCourses": "Khoá học đang học",
    "favoriteCourses": "Khoá học yêu thích",
    "point": "Điểm",
    "type": "Loại người dùng",
    "changePass": "Thay đổi mật khẩu",
    "changeAvt": "Thay đổi ảnh đại diện",
    "phone": "Điện thoại",
    "password": "Mật khẩu",
    "name": "Họ tên",
    "update": "Cập nhật",
    "english": "Tiếng Anh",
    "vietnam": "Tiếng Việt",
    "light": "Tươi sáng",
    "dark": "Bóng tối",
    "instructor": "Giảng viên",
    "placeholderSearch": "Nhập ở đây...",
    "viewAll": "Xem tất cả",
    "viewMore": "Xem thêm",
    "download": "Khoá học đã tải",
    "browse": "Cộng đồng",
    "setting": "Cài đặt",
    "search": "Tìm kiếm",
}

const stringsEnglish = {
    "noti": "Notification",
    "noti_logout": "Do you want to exit app?",
    "option_yes" : "Yes",
    "option-no": "No",
    "category": "Category",
    "author": "Author",
    "price": "Price",
    "updatedAt": "Updated At",
    "rating": "Rating",
    "totalHours": "Total Hours",
    "noData": "No data display",
    "noCourse": "No course display",
    "hour": "hour",
    "recommendCourses": "Recommend for you",
    "topNew": "Top New",
    "topSell": "Top Selling",
    "topRate": "Top Rating",
    "processCourses": "My Learning Courses",
    "favoriteCourses": "My Favorite Courses",
    "point": "Point",
    "type": "Type",
    "changePass": "Change Password",
    "changeAvt": "Change Avatar",
    "phone": "Phone",
    "password": "Password",
    "name": "Full Name",
    "update": "Update",
    "english": "English",
    "vietnam": "Vietnamese",
    "light": "Light",
    "dark": "Dark",
    "instructor": "Instructors",
    "placeholderSearch": "Type something...",
    "viewAll": "See all",
    "viewMore": "See more",
    "download": "Download",
    "browse": "Browser",
    "setting": "Setting",
    "search": "Search",
}

const vietnam = JSON.stringify(stringsVietnam);
const english = JSON.stringify(stringsEnglish);

export { vietnam, english};